FROM mhart/alpine-node:10

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY src /src/
COPY angular.json angular.json
COPY tsconfig.json tsconfig.json

RUN npm install
RUN npm run build
